apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: proyecto-backend-ns
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "TU_AWS_ACCESS_KEY_ID_AQUI"
  AWS_SECRET_ACCESS_KEY: "TU_AWS_SECRET_ACCESS_KEY_AQUI"
