apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: proyecto-backend-ns
data:
  MY_DATABASE_DRIVER: "postgres"
  DB_HOST: "db-host"
  DB_USER_NAME: "root"
  DB_NAME: "proyectodb"
  DB_PORT: "5432"
